android.useAndroidX=true

POM_URL=https://github.com/178meorg/libvlcjni
POM_SCM_URL=https://github.com/178meorg/libvlcjni
POM_SCM_CONNECTION=scm:git:https://github.com/178meorg/libvlcjni.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/178meorg/libvlcjni.git

POM_LICENCE_NAME=GNU Lesser General Public License, version 2.1
POM_LICENCE_URL=https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=178meorg
POM_DEVELOPER_NAME=178meorg
POM_DEVELOPER_URL=https://github.com/178meorg

RELEASE_SIGNING_ENABLED=false

android.newDsl=false
